version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cardsapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cu8ez22jktcl"
s3_prefix = "cardsapi"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
